language: php

before_script:
  - "./scripts/ci/install-reporters.sh"
  - "./scripts/ci/install.sh"
script:
  - ./scripts/ci/ci-$CI_TYPE.sh
install:
  - if [ "$CI_COMPOSER" = "yes" ]; then composer install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress; fi

after_script:
  - if [ "$TRAVIS_BUILD_STAGE_NAME" = "tests" ]; then ./codacy-coverage.phar clover build/logs/clover.xml; else echo "skipped codacy"; fi

stages:
  - name: lint
  - name: tests

jobs:
  include:
    - stage: tests
      php: "7.1"
      env:
        - CI_TYPE=phpunit
        - CI_COMPOSER=yes
      name: "PHPUNIT - PHP 7.1"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF php
    - stage: tests
      php: "7.2"
      env:
        - CI_TYPE=phpunit
        - CI_COMPOSER=yes
      name: "PHPUNIT - PHP 7.2"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF php
    - stage: tests
      php: "7.3"
      env:
        - CI_TYPE=phpunit
        - CI_COMPOSER=yes
      name: "PHPUNIT - PHP 7.3"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF php
    - stage: tests
      os: osx
      language: node_js
      node_js: "10"
      env:
        - CI_TYPE=phpunit
        - CI_COMPOSER=yes
      name: "PHPUNIT - PHP 7.1"
      addons:
        homebrew:
          update: true
          packages:
            - php@7.1
            - composer
      before_install:
        - mkdir ~/.homebrew_logs
        - export HOMEBREW_LOGS="~/.homebrew_logs"
        - export HOMEBREW_TEMP="/tmp"
        - export HOMEBREW_INSTALL_BADGE="🌻"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF php
    - stage: tests
      os: osx
      language: node_js
      node_js: "10"
      env:
        - CI_TYPE=phpunit
        - CI_COMPOSER=yes
      name: "PHPUNIT - PHP 7.2"
      addons:
        homebrew:
          update: true
          packages:
            - php@7.2
            - composer
      before_install:
        - mkdir ~/.homebrew_logs
        - export HOMEBREW_LOGS="~/.homebrew_logs"
        - export HOMEBREW_TEMP="/tmp"
        - export HOMEBREW_INSTALL_BADGE="🌻"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF php
    - stage: tests
      os: osx
      language: node_js
      node_js: "10"
      env:
        - CI_TYPE=phpunit
        - CI_COMPOSER=yes
      name: "PHPUNIT - PHP 7.3"
      addons:
        homebrew:
          update: true
          packages:
            - php@7.3
            - composer
      before_install:
        - echo "memory_limit=-1" > /usr/local/etc/php/7.3/conf.d/50-travis-ci.ini
        - echo "pcre.jit=0" >> /usr/local/etc/php/7.3/conf.d/50-travis-ci.ini
        - mkdir ~/.homebrew_logs
        - export HOMEBREW_LOGS="~/.homebrew_logs"
        - export HOMEBREW_TEMP="/tmp"
        - export HOMEBREW_INSTALL_BADGE="🌻"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF php
    - stage: lint
      php: "7.3"
      env:
        - CI_TYPE=phpstan
        - CI_COMPOSER=yes
      name: "PHPSTAN - PHP 7.3"
    - stage: lint
      php: "7.3"
      env:
        - CI_TYPE=phpcs
        - CI_COMPOSER=yes
      name: "PHPCS - PHP 7.3"

cache:
  ccache: true
  directories:
    - $HOME/.composer/cache/
    - /var/cache/apt
    - $HOME/Library/Caches/Homebrew

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup; fi

addons:
  apt:
    update: false
