name: Lint and analyse files

on: [push]

jobs:
    lint-php:
        runs-on: [self-hosted, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Cache module
              uses: actions/cache@v1.1.2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - uses: php-actions/composer@v4
              with:
                  php_version: latest
                  composer_version: 2
            - name: Lint files
              run: composer run phpcs

    analyse-php:
        runs-on: [self-hosted, ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Cache module
              uses: actions/cache@v1.1.2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - uses: php-actions/composer@v4
              with:
                  php_version: latest
                  composer_version: 2
            - name: Lint files
              run: composer run phpstan
